name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: coursier/cache-action@v8

      - name: Compile
        run: ./mill __.compile

      - name: Run tests
        run: ./mill __.testForked

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v5
      - uses: coursier/cache-action@v8

      - name: Release
        run: ./mill -i mill.scalalib.SonatypeCentralPublishModule/
        env:
          MILL_PGP_SECRET_BASE64: ${{ secrets.PUBLISH_SECRET_KEY }}
          MILL_PGP_PASSPHRASE: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
          MILL_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
